Repository ruzafa8/minishell, pull requests merged in 2023-06, with the labels that each got.

#30 Heredoc
  Makefile
  includes/minishell.h
  src/loop_shell.c
  src/parser/parser/actions_heredoc.c
  src/parser/parser/parser.c
  src/parser/parser/states.c
Labels: enhancement

#35 Bug: Token con strings vacíos
  Makefile
  includes/minishell.h
  src/executer/exec_echo.c
  src/executer/execute.c
  src/loop_shell.c
  src/parser/lexer/actions.c
  src/parser/lexer/lexer.c
  src/parser/lexer/states.c
  src/parser/parser/actions_heredoc.c
  src/utils/expand_variables.c
Labels: bug

#36 33 unset built in
  Makefile
  includes/minishell.h
  src/env/ud_env.c
  src/executer/exec_export.c
  src/executer/exec_unset.c
  src/executer/execute.c
Labels: enhancement

#38 #32: Parser error si termina en REDIR o PIPE
  src/parser/parser/parser.c
Labels: bug

#41 20 control +c +d y +
  Makefile
  includes/minishell.h
  src/loop_shell.c
  src/utils/signals.c
Labels: enhancement

#40 ahora funciona el echo me gusta muchisimo
  src/executer/exec_echo.c
  src/loop_shell.c
Labels: bug

#46 25 errores
  includes/minishell.h
  src/executer/execute.c
  src/executer/execute_utils.c
  src/loop_shell.c
  src/utils/expand_variables.c
Labels: enhancement

#63 58 mover last status a variable global
  includes/minishell.h
  src/executer/execute.c
  src/loop_shell.c
  src/utils/expand_variables.c
  src/utils/init_data.c
Labels: code improvement
